[package]
name = "near-indexer-for-wallet"
version = "0.1.0"
authors = ["Near Inc <hello@nearprotocol.com>"]
edition = "2018"

[dependencies]
actix = "0.9"
bigdecimal = "0.1.0"
diesel = { version = "1.4.4", features = ["postgres", "numeric", "serde_json"] }
diesel-derive-enum = { version = "1", features = ["postgres"] }
dotenv = "0.15.0"
futures = "0.3.5"
itertools = "0.9.0"
r2d2 = "0.8.8"
serde_json = "1.0.55"
tokio = { version = "0.2", features = ["sync", "time"] }
#tokio-diesel = "0.3.0"
tokio-diesel = { git = "https://github.com/frol/tokio-diesel/", branch="fix/blocking-get-0.3.0" }
tracing = "0.1.13"
tracing-subscriber = "0.2.4"

near-indexer = { git = "https://github.com/nearprotocol/nearcore" }